# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'admin.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QAbstractItemView, QAbstractScrollArea, QApplication, QComboBox,
    QDateEdit, QFrame, QGroupBox, QHeaderView,
    QLabel, QLineEdit, QPushButton, QRadioButton,
    QSizePolicy, QStackedWidget, QTableWidget, QTableWidgetItem,
    QTextEdit, QVBoxLayout, QWidget)
import icons_rc
import icons_rc

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.setEnabled(True)
        Form.resize(1250, 790)
        Form.setMinimumSize(QSize(1250, 790))
        Form.setMaximumSize(QSize(1250, 790))
        Form.setAcceptDrops(False)
        Form.setAutoFillBackground(False)
        Form.setStyleSheet(u"QWidget#Form{\n"
"	background-color:#fff/*rgb(37, 150, 190)*/;\n"
"}\n"
"QLabel[statusTip = \"this\"]{\n"
"	color:black;\n"
"}\n"
"QHBoxLayout{\n"
"	background-color:black;\n"
"}\n"
"QFrame[statusTip = \"option\"]{\n"
"\n"
" }\n"
"\n"
"QFrame[statusTip = \"option\"][enabled = \"true\"]:hover{\n"
"	background-color: rgba(110, 110, 110,80);\n"
"	border-left: 6px solid #154c79;\n"
" }\n"
"QFrame[statusTip = \"option\"][enabled = \"false\"]{\n"
"	background-color: rgba(110, 110, 110, 80);\n"
"	border-left: 6px solid #154c79;\n"
" }\n"
"")
        self.groupBox = QGroupBox(Form)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 10, 201, 151))
        self.groupBox.setStyleSheet(u"border: none;")
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(60, 10, 91, 81))
        self.label.setPixmap(QPixmap(u":/icons/admin.png"))
        self.label.setScaledContents(True)
        self.admin_name_lbl = QLabel(self.groupBox)
        self.admin_name_lbl.setObjectName(u"admin_name_lbl")
        self.admin_name_lbl.setGeometry(QRect(30, 90, 151, 31))
        self.admin_name_lbl.setStyleSheet(u"font-size: 15px;\n"
"font: bold;")
        self.admin_name_lbl.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(70, 120, 71, 20))
        self.label_3.setStyleSheet(u"font-size : 20px;\n"
"font:bold;")
        self.containor = QStackedWidget(Form)
        self.containor.setObjectName(u"containor")
        self.containor.setGeometry(QRect(260, 20, 961, 751))
        self.containor.setStyleSheet(u"QStackedWidget{\n"
"	background-color:#fff;\n"
"}\n"
"QPushButton[statusTip = \"btn_frm\"]{\n"
"	background-color : #154c79;\n"
"	color: rgba(255 , 255, 255, 210);\n"
"	border-radius: 10px;\n"
"	font-size: 15px;\n"
"	font : bold;\n"
" }\n"
"QPushButton[statusTip = \"btn_frm\"]:hover{\n"
"	background-color : rgba(0, 21, 76, 200);\n"
"	color: rgba(255 , 255, 255, 210);\n"
"	border-radius: 10px;\n"
"	font-size: 15px;\n"
"	font : bold;\n"
" }\n"
"QPushButton[statusTip = \"btn_frm\"]:pressed{\n"
"	background-color : rgba(0, 21, 76, 200);\n"
"	color: rgba(255 , 255, 255, 210);\n"
"	border-radius: 13px;\n"
"	font-size: 15px;\n"
"	padding-top: 2px;\n"
"	font : bold;\n"
" }\n"
"QTableWidget{\n"
"	alternate-background-color: rgba(21, 76, 121, 120);\n"
"	background-color: rgba(21, 76, 121, 80);\n"
"}\n"
"\n"
"")
        self.containor.setInputMethodHints(Qt.ImhDialableCharactersOnly|Qt.ImhDigitsOnly|Qt.ImhEmailCharactersOnly|Qt.ImhFormattedNumbersOnly|Qt.ImhLatinOnly|Qt.ImhLowercaseOnly|Qt.ImhUppercaseOnly|Qt.ImhUrlCharactersOnly)
        self.stats_frame = QWidget()
        self.stats_frame.setObjectName(u"stats_frame")
        self.stats_frame.setAutoFillBackground(False)
        self.label_18 = QLabel(self.stats_frame)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(270, 220, 181, 81))
        self.label_18.setStyleSheet(u"font-size: 50px;")
        self.containor.addWidget(self.stats_frame)
        self.products_frame = QWidget()
        self.products_frame.setObjectName(u"products_frame")
        self.tableWidget = QTableWidget(self.products_frame)
        if (self.tableWidget.columnCount() < 5):
            self.tableWidget.setColumnCount(5)
        __qtablewidgetitem = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, __qtablewidgetitem)
        __qtablewidgetitem1 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, __qtablewidgetitem1)
        __qtablewidgetitem2 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, __qtablewidgetitem2)
        __qtablewidgetitem3 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, __qtablewidgetitem3)
        __qtablewidgetitem4 = QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, __qtablewidgetitem4)
        self.tableWidget.setObjectName(u"tableWidget")
        self.tableWidget.setEnabled(True)
        self.tableWidget.setGeometry(QRect(320, 40, 631, 701))
        self.tableWidget.setContextMenuPolicy(Qt.PreventContextMenu)
        self.tableWidget.setAcceptDrops(False)
#if QT_CONFIG(statustip)
        self.tableWidget.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.tableWidget.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setGridStyle(Qt.SolidLine)
        self.tableWidget.setCornerButtonEnabled(False)
        self.label_19 = QLabel(self.products_frame)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 290, 51, 31))
        font = QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_24 = QLabel(self.products_frame)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 350, 41, 31))
        self.label_24.setFont(font)
        self.label_25 = QLabel(self.products_frame)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 420, 71, 31))
        self.label_25.setFont(font)
        self.label_26 = QLabel(self.products_frame)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 230, 51, 31))
        self.label_26.setFont(font)
        self.product_id = QLineEdit(self.products_frame)
        self.product_id.setObjectName(u"product_id")
        self.product_id.setGeometry(QRect(110, 220, 191, 41))
        self.product_id.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.product_name = QLineEdit(self.products_frame)
        self.product_name.setObjectName(u"product_name")
        self.product_name.setGeometry(QRect(110, 280, 191, 41))
        self.product_name.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.product_price = QLineEdit(self.products_frame)
        self.product_price.setObjectName(u"product_price")
        self.product_price.setGeometry(QRect(110, 340, 191, 41))
        self.product_price.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.product_quantity = QLineEdit(self.products_frame)
        self.product_quantity.setObjectName(u"product_quantity")
        self.product_quantity.setGeometry(QRect(110, 410, 191, 41))
        self.product_quantity.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.add_btn = QPushButton(self.products_frame)
        self.add_btn.setObjectName(u"add_btn")
        self.add_btn.setGeometry(QRect(10, 640, 91, 41))
        self.add_btn.setStyleSheet(u"")
        self.update_btn = QPushButton(self.products_frame)
        self.update_btn.setObjectName(u"update_btn")
        self.update_btn.setGeometry(QRect(110, 640, 91, 41))
        self.update_btn.setStyleSheet(u"")
        self.delete_btn = QPushButton(self.products_frame)
        self.delete_btn.setObjectName(u"delete_btn")
        self.delete_btn.setGeometry(QRect(210, 640, 91, 41))
        self.delete_btn.setStyleSheet(u"")
        self.product_category = QComboBox(self.products_frame)
        self.product_category.addItem("")
        self.product_category.addItem("")
        self.product_category.addItem("")
        self.product_category.addItem("")
        self.product_category.setObjectName(u"product_category")
        self.product_category.setGeometry(QRect(20, 480, 281, 31))
        sizePolicy = QSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.product_category.sizePolicy().hasHeightForWidth())
        self.product_category.setSizePolicy(sizePolicy)
        self.product_category.setFont(font)
        self.product_category.setTabletTracking(False)
        self.product_category.setStyleSheet(u"QComboBox {\n"
"    border: 2px solid #154c79;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"color :#154c79;\n"
"}\n"
"QComboBox::down-arrow {\n"
"	border: 0px;\n"
"    background-repeat: no-repeat;\n"
"    background-position: center center;\n"
"    border-image: url(:/icons/down-arrow.png);\n"
"	\n"
"}")
        self.product_category.setInsertPolicy(QComboBox.InsertAtBottom)
        self.product_category.setIconSize(QSize(30, 30))
        self.clear_btn = QPushButton(self.products_frame)
        self.clear_btn.setObjectName(u"clear_btn")
        self.clear_btn.setGeometry(QRect(230, 530, 71, 31))
        self.clear_btn.setStyleSheet(u"")
        self.label_16 = QLabel(self.products_frame)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(90, 60, 141, 131))
        self.label_16.setPixmap(QPixmap(u":/icons/products_c.png"))
        self.label_16.setScaledContents(True)
        self.label_17 = QLabel(self.products_frame)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(110, 20, 91, 31))
        self.label_17.setStyleSheet(u"color: #154c79;\n"
"font-size: 20px;\n"
"font: bold;\n"
"")
        self.products_search_btn = QPushButton(self.products_frame)
        self.products_search_btn.setObjectName(u"products_search_btn")
        self.products_search_btn.setGeometry(QRect(150, 530, 71, 31))
        self.products_search_btn.setStyleSheet(u"")
        self.containor.addWidget(self.products_frame)
        self.categories_frame = QWidget()
        self.categories_frame.setObjectName(u"categories_frame")
        self.label_27 = QLabel(self.categories_frame)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(110, 20, 111, 31))
        self.label_27.setStyleSheet(u"color: #154c79;\n"
"font-size: 20px;\n"
"font: bold;\n"
"")
        self.label_20 = QLabel(self.categories_frame)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(90, 60, 141, 131))
        self.label_20.setPixmap(QPixmap(u":/icons/categories_c.png"))
        self.label_20.setScaledContents(True)
        self.category_name = QLineEdit(self.categories_frame)
        self.category_name.setObjectName(u"category_name")
        self.category_name.setGeometry(QRect(110, 330, 191, 41))
        self.category_name.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.category_id = QLineEdit(self.categories_frame)
        self.category_id.setObjectName(u"category_id")
        self.category_id.setGeometry(QRect(110, 270, 191, 41))
        self.category_id.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_28 = QLabel(self.categories_frame)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(20, 400, 91, 31))
        self.label_28.setFont(font)
        self.label_29 = QLabel(self.categories_frame)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(20, 340, 51, 31))
        self.label_29.setFont(font)
        self.label_30 = QLabel(self.categories_frame)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 280, 51, 31))
        self.label_30.setFont(font)
        self.categories_clear_btn = QPushButton(self.categories_frame)
        self.categories_clear_btn.setObjectName(u"categories_clear_btn")
        self.categories_clear_btn.setGeometry(QRect(230, 510, 71, 31))
        self.categories_clear_btn.setStyleSheet(u"")
        self.categories_add_btn = QPushButton(self.categories_frame)
        self.categories_add_btn.setObjectName(u"categories_add_btn")
        self.categories_add_btn.setGeometry(QRect(20, 570, 91, 41))
        self.categories_add_btn.setStyleSheet(u"")
        self.categories_update_btn = QPushButton(self.categories_frame)
        self.categories_update_btn.setObjectName(u"categories_update_btn")
        self.categories_update_btn.setGeometry(QRect(120, 570, 91, 41))
        self.categories_update_btn.setStyleSheet(u"")
        self.categories_delete_btn = QPushButton(self.categories_frame)
        self.categories_delete_btn.setObjectName(u"categories_delete_btn")
        self.categories_delete_btn.setGeometry(QRect(220, 570, 91, 41))
        self.categories_delete_btn.setStyleSheet(u"")
        self.tableWidget_2 = QTableWidget(self.categories_frame)
        if (self.tableWidget_2.columnCount() < 3):
            self.tableWidget_2.setColumnCount(3)
        __qtablewidgetitem5 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, __qtablewidgetitem5)
        __qtablewidgetitem6 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, __qtablewidgetitem6)
        __qtablewidgetitem7 = QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, __qtablewidgetitem7)
        self.tableWidget_2.setObjectName(u"tableWidget_2")
        self.tableWidget_2.setEnabled(True)
        self.tableWidget_2.setGeometry(QRect(320, 40, 631, 691))
        self.tableWidget_2.setContextMenuPolicy(Qt.PreventContextMenu)
        self.tableWidget_2.setAcceptDrops(False)
#if QT_CONFIG(statustip)
        self.tableWidget_2.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.tableWidget_2.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_2.setAutoFillBackground(True)
        self.tableWidget_2.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_2.setAlternatingRowColors(True)
        self.tableWidget_2.setGridStyle(Qt.SolidLine)
        self.tableWidget_2.setCornerButtonEnabled(False)
        self.tableWidget_2.horizontalHeader().setDefaultSectionSize(209)
        self.categories_search_btn = QPushButton(self.categories_frame)
        self.categories_search_btn.setObjectName(u"categories_search_btn")
        self.categories_search_btn.setGeometry(QRect(150, 510, 71, 31))
        self.categories_search_btn.setStyleSheet(u"")
        self.textEdit_2 = QTextEdit(self.categories_frame)
        self.textEdit_2.setObjectName(u"textEdit_2")
        self.textEdit_2.setGeometry(QRect(110, 400, 191, 91))
        self.textEdit_2.setStyleSheet(u"border: 2px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.containor.addWidget(self.categories_frame)
        self.users_frame = QWidget()
        self.users_frame.setObjectName(u"users_frame")
        self.label_31 = QLabel(self.users_frame)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(170, 30, 111, 31))
        self.label_31.setFont(font)
        self.users_id = QLineEdit(self.users_frame)
        self.users_id.setObjectName(u"users_id")
        self.users_id.setGeometry(QRect(270, 20, 191, 41))
        self.users_id.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.users_id.setReadOnly(True)
        self.label_32 = QLabel(self.users_frame)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(170, 90, 91, 31))
        self.label_32.setFont(font)
        self.label_33 = QLabel(self.users_frame)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(170, 150, 91, 31))
        self.label_33.setFont(font)
        self.users_birth_date = QDateEdit(self.users_frame)
        self.users_birth_date.setObjectName(u"users_birth_date")
        self.users_birth_date.setGeometry(QRect(130, 200, 171, 31))
        self.users_birth_date.setAcceptDrops(False)
        self.users_birth_date.setStyleSheet(u"border: 2px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.users_birth_date.setAccelerated(False)
        self.users_birth_date.setCalendarPopup(True)
        self.users_first_name = QLineEdit(self.users_frame)
        self.users_first_name.setObjectName(u"users_first_name")
        self.users_first_name.setGeometry(QRect(270, 80, 191, 41))
        self.users_first_name.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.users_last_name = QLineEdit(self.users_frame)
        self.users_last_name.setObjectName(u"users_last_name")
        self.users_last_name.setGeometry(QRect(270, 140, 191, 41))
        self.users_last_name.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_34 = QLabel(self.users_frame)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(10, 200, 91, 31))
        self.label_34.setFont(font)
        self.label_35 = QLabel(self.users_frame)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(330, 200, 61, 31))
        self.label_35.setFont(font)
        self.users_male = QRadioButton(self.users_frame)
        self.users_male.setObjectName(u"users_male")
        self.users_male.setGeometry(QRect(410, 200, 71, 31))
        self.users_male.setStyleSheet(u"color: #154c79;\n"
"font-size: 18px;")
        self.users_male.setChecked(True)
        self.users_female = QRadioButton(self.users_frame)
        self.users_female.setObjectName(u"users_female")
        self.users_female.setGeometry(QRect(490, 200, 81, 31))
        self.users_female.setStyleSheet(u"color: #154c79;\n"
"font-size: 18px;")
        self.label_36 = QLabel(self.users_frame)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(630, 0, 161, 31))
        self.label_36.setStyleSheet(u"color: #154c79;\n"
"font-size: 20px;\n"
"font: bold;\n"
"")
        self.label_37 = QLabel(self.users_frame)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(580, 50, 91, 31))
        self.label_37.setFont(font)
        self.users_user_name = QLineEdit(self.users_frame)
        self.users_user_name.setObjectName(u"users_user_name")
        self.users_user_name.setGeometry(QRect(690, 40, 241, 41))
        self.users_user_name.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_38 = QLabel(self.users_frame)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(580, 100, 91, 31))
        self.label_38.setFont(font)
        self.users_password = QLineEdit(self.users_frame)
        self.users_password.setObjectName(u"users_password")
        self.users_password.setGeometry(QRect(690, 90, 241, 41))
        self.users_password.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_39 = QLabel(self.users_frame)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(580, 160, 51, 31))
        self.label_39.setFont(font)
        self.users_role = QComboBox(self.users_frame)
        self.users_role.addItem("")
        self.users_role.addItem("")
        self.users_role.setObjectName(u"users_role")
        self.users_role.setGeometry(QRect(690, 160, 241, 31))
        self.users_role.setStyleSheet(u"color: #154c79;\n"
"font-size: 18px;\n"
"border: 2px solid #154c79;")
        self.label_40 = QLabel(self.users_frame)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(10, 250, 111, 31))
        self.label_40.setFont(font)
        self.users_phone_number = QLineEdit(self.users_frame)
        self.users_phone_number.setObjectName(u"users_phone_number")
        self.users_phone_number.setGeometry(QRect(130, 240, 171, 41))
        self.users_phone_number.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_41 = QLabel(self.users_frame)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 300, 81, 31))
        self.label_41.setFont(font)
        self.users_salary = QLineEdit(self.users_frame)
        self.users_salary.setObjectName(u"users_salary")
        self.users_salary.setGeometry(QRect(130, 290, 171, 41))
        self.users_salary.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_42 = QLabel(self.users_frame)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(330, 250, 61, 31))
        self.label_42.setFont(font)
        self.users_adress = QTextEdit(self.users_frame)
        self.users_adress.setObjectName(u"users_adress")
        self.users_adress.setGeometry(QRect(400, 250, 171, 71))
        self.users_adress.setStyleSheet(u"border: 2px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_21 = QLabel(self.users_frame)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(10, 50, 141, 131))
        self.label_21.setPixmap(QPixmap(u":/icons/employee_c.png"))
        self.label_21.setScaledContents(True)
        self.label_43 = QLabel(self.users_frame)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(50, 0, 61, 31))
        self.label_43.setStyleSheet(u"color: #154c79;\n"
"font-size: 20px;\n"
"font: bold;\n"
"")
        self.users_add_btn = QPushButton(self.users_frame)
        self.users_add_btn.setObjectName(u"users_add_btn")
        self.users_add_btn.setGeometry(QRect(700, 210, 71, 41))
        self.users_add_btn.setStyleSheet(u"")
        self.users_update_btn = QPushButton(self.users_frame)
        self.users_update_btn.setObjectName(u"users_update_btn")
        self.users_update_btn.setGeometry(QRect(780, 210, 71, 41))
        self.users_update_btn.setStyleSheet(u"")
        self.users_delete_btn = QPushButton(self.users_frame)
        self.users_delete_btn.setObjectName(u"users_delete_btn")
        self.users_delete_btn.setGeometry(QRect(860, 210, 71, 41))
        self.users_delete_btn.setStyleSheet(u"")
        self.users_clear_btn = QPushButton(self.users_frame)
        self.users_clear_btn.setObjectName(u"users_clear_btn")
        self.users_clear_btn.setGeometry(QRect(580, 290, 71, 31))
        self.users_clear_btn.setStyleSheet(u"")
        self.users_search_btn = QPushButton(self.users_frame)
        self.users_search_btn.setObjectName(u"users_search_btn")
        self.users_search_btn.setGeometry(QRect(860, 290, 71, 31))
        self.users_search_btn.setStyleSheet(u"")
        self.users_table = QTableWidget(self.users_frame)
        if (self.users_table.columnCount() < 11):
            self.users_table.setColumnCount(11)
        font1 = QFont()
        font1.setStyleStrategy(QFont.PreferAntialias)
        __qtablewidgetitem8 = QTableWidgetItem()
        __qtablewidgetitem8.setFont(font1);
        self.users_table.setHorizontalHeaderItem(0, __qtablewidgetitem8)
        __qtablewidgetitem9 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(1, __qtablewidgetitem9)
        __qtablewidgetitem10 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(2, __qtablewidgetitem10)
        __qtablewidgetitem11 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(3, __qtablewidgetitem11)
        __qtablewidgetitem12 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(4, __qtablewidgetitem12)
        __qtablewidgetitem13 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(5, __qtablewidgetitem13)
        __qtablewidgetitem14 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(6, __qtablewidgetitem14)
        __qtablewidgetitem15 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(7, __qtablewidgetitem15)
        __qtablewidgetitem16 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(8, __qtablewidgetitem16)
        __qtablewidgetitem17 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(9, __qtablewidgetitem17)
        __qtablewidgetitem18 = QTableWidgetItem()
        self.users_table.setHorizontalHeaderItem(10, __qtablewidgetitem18)
        self.users_table.setObjectName(u"users_table")
        self.users_table.setEnabled(True)
        self.users_table.setGeometry(QRect(20, 340, 921, 401))
        self.users_table.setMinimumSize(QSize(511, 401))
        self.users_table.setMaximumSize(QSize(999999, 999999))
        font2 = QFont()
        font2.setKerning(True)
        self.users_table.setFont(font2)
        self.users_table.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.users_table.setTabKeyNavigation(False)
        self.users_table.setProperty("showDropIndicator", False)
        self.users_table.setDragEnabled(False)
        self.users_table.setDragDropOverwriteMode(False)
        self.users_table.setDragDropMode(QAbstractItemView.NoDragDrop)
        self.users_table.setSelectionMode(QAbstractItemView.SingleSelection)
        self.users_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.users_table.setTextElideMode(Qt.ElideRight)
        self.users_table.setShowGrid(True)
        self.users_table.setSortingEnabled(False)
        self.users_table.setCornerButtonEnabled(False)
        self.users_table.horizontalHeader().setVisible(False)
        self.users_table.horizontalHeader().setMinimumSectionSize(83)
        self.users_table.horizontalHeader().setDefaultSectionSize(83)
        self.users_table.horizontalHeader().setHighlightSections(False)
        self.users_table.horizontalHeader().setProperty("showSortIndicator", False)
        self.users_table.verticalHeader().setVisible(False)
        self.users_table.verticalHeader().setCascadingSectionResizes(False)
        self.users_table.verticalHeader().setMinimumSectionSize(51)
        self.users_table.verticalHeader().setDefaultSectionSize(30)
        self.users_table.verticalHeader().setHighlightSections(False)
        self.users_table.verticalHeader().setProperty("showSortIndicator", False)
        self.users_table.verticalHeader().setStretchLastSection(False)
        self.users_search_id = QLineEdit(self.users_frame)
        self.users_search_id.setObjectName(u"users_search_id")
        self.users_search_id.setGeometry(QRect(760, 290, 91, 31))
        self.users_search_id.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.users_search_id.setReadOnly(False)
        self.containor.addWidget(self.users_frame)
        self.incomes_frame = QWidget()
        self.incomes_frame.setObjectName(u"incomes_frame")
        self.label_44 = QLabel(self.incomes_frame)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(110, 70, 141, 131))
        self.label_44.setPixmap(QPixmap(u":/icons/sellings_c.png"))
        self.label_44.setScaledContents(True)
        self.label_45 = QLabel(self.incomes_frame)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(140, 10, 91, 31))
        self.label_45.setStyleSheet(u"color: #154c79;\n"
"font-size: 20px;\n"
"font: bold;\n"
"")
        self.label_46 = QLabel(self.incomes_frame)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(330, 50, 31, 31))
        self.label_46.setFont(font)
        self.categorie_id_9 = QLineEdit(self.incomes_frame)
        self.categorie_id_9.setObjectName(u"categorie_id_9")
        self.categorie_id_9.setGeometry(QRect(440, 40, 161, 41))
        self.categorie_id_9.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_47 = QLabel(self.incomes_frame)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(330, 100, 91, 31))
        self.label_47.setFont(font)
        self.label_48 = QLabel(self.incomes_frame)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(670, 50, 41, 31))
        self.label_48.setFont(font)
        self.label_49 = QLabel(self.incomes_frame)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(670, 100, 91, 31))
        self.label_49.setFont(font)
        self.categorie_id_10 = QLineEdit(self.incomes_frame)
        self.categorie_id_10.setObjectName(u"categorie_id_10")
        self.categorie_id_10.setGeometry(QRect(440, 90, 161, 41))
        self.categorie_id_10.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.categorie_id_11 = QLineEdit(self.incomes_frame)
        self.categorie_id_11.setObjectName(u"categorie_id_11")
        self.categorie_id_11.setGeometry(QRect(780, 40, 161, 41))
        self.categorie_id_11.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.categorie_id_12 = QLineEdit(self.incomes_frame)
        self.categorie_id_12.setObjectName(u"categorie_id_12")
        self.categorie_id_12.setGeometry(QRect(780, 90, 161, 41))
        self.categorie_id_12.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.sellings_search_btn = QPushButton(self.incomes_frame)
        self.sellings_search_btn.setObjectName(u"sellings_search_btn")
        self.sellings_search_btn.setGeometry(QRect(810, 170, 131, 41))
        self.sellings_search_btn.setStyleSheet(u"")
        self.sellings_delete_btn = QPushButton(self.incomes_frame)
        self.sellings_delete_btn.setObjectName(u"sellings_delete_btn")
        self.sellings_delete_btn.setGeometry(QRect(660, 170, 131, 41))
        self.sellings_delete_btn.setStyleSheet(u"")
        self.tableWidget_4 = QTableWidget(self.incomes_frame)
        if (self.tableWidget_4.columnCount() < 4):
            self.tableWidget_4.setColumnCount(4)
        __qtablewidgetitem19 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(0, __qtablewidgetitem19)
        __qtablewidgetitem20 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(1, __qtablewidgetitem20)
        __qtablewidgetitem21 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(2, __qtablewidgetitem21)
        __qtablewidgetitem22 = QTableWidgetItem()
        self.tableWidget_4.setHorizontalHeaderItem(3, __qtablewidgetitem22)
        if (self.tableWidget_4.rowCount() < 18):
            self.tableWidget_4.setRowCount(18)
        __qtablewidgetitem23 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(0, __qtablewidgetitem23)
        __qtablewidgetitem24 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(1, __qtablewidgetitem24)
        __qtablewidgetitem25 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(2, __qtablewidgetitem25)
        __qtablewidgetitem26 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(3, __qtablewidgetitem26)
        __qtablewidgetitem27 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(4, __qtablewidgetitem27)
        __qtablewidgetitem28 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(5, __qtablewidgetitem28)
        __qtablewidgetitem29 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(6, __qtablewidgetitem29)
        __qtablewidgetitem30 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(7, __qtablewidgetitem30)
        __qtablewidgetitem31 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(8, __qtablewidgetitem31)
        __qtablewidgetitem32 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(9, __qtablewidgetitem32)
        __qtablewidgetitem33 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(10, __qtablewidgetitem33)
        __qtablewidgetitem34 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(11, __qtablewidgetitem34)
        __qtablewidgetitem35 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(12, __qtablewidgetitem35)
        __qtablewidgetitem36 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(13, __qtablewidgetitem36)
        __qtablewidgetitem37 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(14, __qtablewidgetitem37)
        __qtablewidgetitem38 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(15, __qtablewidgetitem38)
        __qtablewidgetitem39 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(16, __qtablewidgetitem39)
        __qtablewidgetitem40 = QTableWidgetItem()
        self.tableWidget_4.setVerticalHeaderItem(17, __qtablewidgetitem40)
        self.tableWidget_4.setObjectName(u"tableWidget_4")
        self.tableWidget_4.setEnabled(True)
        self.tableWidget_4.setGeometry(QRect(20, 240, 921, 491))
        sizePolicy1 = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.tableWidget_4.sizePolicy().hasHeightForWidth())
        self.tableWidget_4.setSizePolicy(sizePolicy1)
        self.tableWidget_4.setBaseSize(QSize(0, 0))
        font3 = QFont()
        font3.setFamilies([u"Nirmala UI Semilight"])
        font3.setStyleStrategy(QFont.PreferDefault)
        self.tableWidget_4.setFont(font3)
        self.tableWidget_4.setMouseTracking(True)
        self.tableWidget_4.setTabletTracking(True)
        self.tableWidget_4.setFocusPolicy(Qt.TabFocus)
        self.tableWidget_4.setContextMenuPolicy(Qt.ActionsContextMenu)
        self.tableWidget_4.setAcceptDrops(False)
        self.tableWidget_4.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_4.setAutoFillBackground(False)
        self.tableWidget_4.setStyleSheet(u"")
        self.tableWidget_4.setFrameShape(QFrame.Panel)
        self.tableWidget_4.setFrameShadow(QFrame.Plain)
        self.tableWidget_4.setLineWidth(0)
        self.tableWidget_4.setAutoScroll(True)
        self.tableWidget_4.setTabKeyNavigation(True)
        self.tableWidget_4.setProperty("showDropIndicator", False)
        self.tableWidget_4.setDragEnabled(False)
        self.tableWidget_4.setDragDropOverwriteMode(False)
        self.tableWidget_4.setDragDropMode(QAbstractItemView.NoDragDrop)
        self.tableWidget_4.setDefaultDropAction(Qt.IgnoreAction)
        self.tableWidget_4.setAlternatingRowColors(True)
        self.tableWidget_4.setSelectionMode(QAbstractItemView.SingleSelection)
        self.tableWidget_4.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.tableWidget_4.setTextElideMode(Qt.ElideMiddle)
        self.tableWidget_4.setShowGrid(True)
        self.tableWidget_4.setGridStyle(Qt.SolidLine)
        self.tableWidget_4.setSortingEnabled(True)
        self.tableWidget_4.setWordWrap(True)
        self.tableWidget_4.setCornerButtonEnabled(False)
        self.tableWidget_4.setColumnCount(4)
        self.tableWidget_4.horizontalHeader().setVisible(False)
        self.tableWidget_4.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget_4.horizontalHeader().setMinimumSectionSize(216)
        self.tableWidget_4.horizontalHeader().setDefaultSectionSize(216)
        self.tableWidget_4.horizontalHeader().setProperty("showSortIndicator", True)
        self.tableWidget_4.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_4.verticalHeader().setVisible(False)
        self.tableWidget_4.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget_4.verticalHeader().setDefaultSectionSize(40)
        self.tableWidget_4.verticalHeader().setHighlightSections(True)
        self.tableWidget_4.verticalHeader().setProperty("showSortIndicator", False)
        self.tableWidget_4.verticalHeader().setStretchLastSection(False)
        self.containor.addWidget(self.incomes_frame)
        self.expenses_frame = QWidget()
        self.expenses_frame.setObjectName(u"expenses_frame")
        self.label_50 = QLabel(self.expenses_frame)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(100, 70, 141, 131))
        self.label_50.setPixmap(QPixmap(u":/icons/bills_c.png"))
        self.label_50.setScaledContents(True)
        self.label_51 = QLabel(self.expenses_frame)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(120, 20, 101, 31))
        self.label_51.setStyleSheet(u"color: #154c79;\n"
"font-size: 20px;\n"
"font: bold;\n"
"")
        self.expense_delete_btn = QPushButton(self.expenses_frame)
        self.expense_delete_btn.setObjectName(u"expense_delete_btn")
        self.expense_delete_btn.setGeometry(QRect(210, 630, 91, 41))
        self.expense_delete_btn.setStyleSheet(u"")
        self.expense_id = QLineEdit(self.expenses_frame)
        self.expense_id.setObjectName(u"expense_id")
        self.expense_id.setGeometry(QRect(110, 250, 191, 41))
        self.expense_id.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.expense_id.setInputMethodHints(Qt.ImhDigitsOnly)
        self.label_52 = QLabel(self.expenses_frame)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(10, 260, 51, 31))
        self.label_52.setFont(font)
        self.label_53 = QLabel(self.expenses_frame)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(10, 320, 81, 31))
        self.label_53.setFont(font)
        self.tableWidget_5 = QTableWidget(self.expenses_frame)
        if (self.tableWidget_5.columnCount() < 5):
            self.tableWidget_5.setColumnCount(5)
        __qtablewidgetitem41 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(0, __qtablewidgetitem41)
        __qtablewidgetitem42 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(1, __qtablewidgetitem42)
        __qtablewidgetitem43 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(2, __qtablewidgetitem43)
        __qtablewidgetitem44 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(3, __qtablewidgetitem44)
        __qtablewidgetitem45 = QTableWidgetItem()
        self.tableWidget_5.setHorizontalHeaderItem(4, __qtablewidgetitem45)
        self.tableWidget_5.setObjectName(u"tableWidget_5")
        self.tableWidget_5.setEnabled(True)
        self.tableWidget_5.setGeometry(QRect(320, 20, 631, 661))
        self.tableWidget_5.setContextMenuPolicy(Qt.PreventContextMenu)
        self.tableWidget_5.setAcceptDrops(False)
#if QT_CONFIG(statustip)
        self.tableWidget_5.setStatusTip(u"")
#endif // QT_CONFIG(statustip)
        self.tableWidget_5.setLayoutDirection(Qt.LeftToRight)
        self.tableWidget_5.setAutoFillBackground(True)
        self.tableWidget_5.setSizeAdjustPolicy(QAbstractScrollArea.AdjustToContents)
        self.tableWidget_5.setAlternatingRowColors(True)
        self.tableWidget_5.setGridStyle(Qt.SolidLine)
        self.tableWidget_5.setCornerButtonEnabled(False)
        self.expense_clear_btn = QPushButton(self.expenses_frame)
        self.expense_clear_btn.setObjectName(u"expense_clear_btn")
        self.expense_clear_btn.setGeometry(QRect(230, 570, 71, 31))
        self.expense_clear_btn.setStyleSheet(u"")
        self.expense_update_btn = QPushButton(self.expenses_frame)
        self.expense_update_btn.setObjectName(u"expense_update_btn")
        self.expense_update_btn.setGeometry(QRect(110, 630, 91, 41))
        self.expense_update_btn.setStyleSheet(u"")
        self.expense_search_btn = QPushButton(self.expenses_frame)
        self.expense_search_btn.setObjectName(u"expense_search_btn")
        self.expense_search_btn.setGeometry(QRect(150, 570, 71, 31))
        self.expense_search_btn.setStyleSheet(u"")
        self.expense_description = QTextEdit(self.expenses_frame)
        self.expense_description.setObjectName(u"expense_description")
        self.expense_description.setGeometry(QRect(110, 470, 191, 91))
        self.expense_description.setStyleSheet(u"border: 2px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.label_54 = QLabel(self.expenses_frame)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(10, 470, 91, 31))
        self.label_54.setFont(font)
        self.expense_ammount = QLineEdit(self.expenses_frame)
        self.expense_ammount.setObjectName(u"expense_ammount")
        self.expense_ammount.setGeometry(QRect(110, 310, 191, 41))
        self.expense_ammount.setStyleSheet(u"border: none;\n"
"border-bottom: 3px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.expense_ammount.setInputMethodHints(Qt.ImhDigitsOnly)
        self.expense_add_btn = QPushButton(self.expenses_frame)
        self.expense_add_btn.setObjectName(u"expense_add_btn")
        self.expense_add_btn.setGeometry(QRect(10, 630, 91, 41))
        self.expense_add_btn.setStyleSheet(u"")
        self.expense_type = QComboBox(self.expenses_frame)
        self.expense_type.addItem("")
        self.expense_type.addItem("")
        self.expense_type.setObjectName(u"expense_type")
        self.expense_type.setGeometry(QRect(110, 370, 191, 31))
        self.expense_type.setStyleSheet(u"color: #154c79;\n"
"font-size: 18px;\n"
"border: 2px solid #154c79;")
        self.label_55 = QLabel(self.expenses_frame)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(10, 370, 81, 31))
        self.label_55.setFont(font)
        self.expense_date = QDateEdit(self.expenses_frame)
        self.expense_date.setObjectName(u"expense_date")
        self.expense_date.setGeometry(QRect(110, 420, 191, 31))
        self.expense_date.setAcceptDrops(False)
        self.expense_date.setStyleSheet(u"border: 2px solid #154c79;\n"
"color: #154c79;\n"
"font-size: 18px;")
        self.expense_date.setAccelerated(False)
        self.expense_date.setCalendarPopup(True)
        self.label_56 = QLabel(self.expenses_frame)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(10, 420, 81, 31))
        self.label_56.setFont(font)
        self.containor.addWidget(self.expenses_frame)
        self.line = QFrame(Form)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(240, 20, 31, 761))
        sizePolicy2 = QSizePolicy(QSizePolicy.Minimum, QSizePolicy.Minimum)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(3)
        sizePolicy2.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy2)
        self.line.setFont(font)
        self.line.setStyleSheet(u"color: #154c79;")
        self.line.setFrameShadow(QFrame.Plain)
        self.line.setFrameShape(QFrame.VLine)
        self.verticalLayoutWidget = QWidget(Form)
        self.verticalLayoutWidget.setObjectName(u"verticalLayoutWidget")
        self.verticalLayoutWidget.setGeometry(QRect(10, 180, 241, 511))
        self.options = QVBoxLayout(self.verticalLayoutWidget)
        self.options.setObjectName(u"options")
        self.options.setContentsMargins(0, 0, 0, 0)
        self.stats_lbl = QFrame(self.verticalLayoutWidget)
        self.stats_lbl.setObjectName(u"stats_lbl")
        self.stats_lbl.setEnabled(False)
        self.stats_lbl.setFrameShape(QFrame.StyledPanel)
        self.stats_lbl.setFrameShadow(QFrame.Raised)
        self.label_5 = QLabel(self.stats_lbl)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(110, 10, 71, 51))
        self.label_5.setBaseSize(QSize(50, 20))
        font4 = QFont()
        font4.setFamilies([u"Segoe UI Semibold"])
        font4.setPointSize(15)
        font4.setBold(True)
        self.label_5.setFont(font4)
        self.label_5.setAutoFillBackground(False)
        self.label_5.setStyleSheet(u"")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.label_4 = QLabel(self.stats_lbl)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 10, 51, 51))
        self.label_4.setMaximumSize(QSize(51, 51))
        self.label_4.setBaseSize(QSize(30, 30))
        font5 = QFont()
        font5.setStrikeOut(False)
        font5.setStyleStrategy(QFont.PreferDefault)
        self.label_4.setFont(font5)
        self.label_4.setPixmap(QPixmap(u":/icons/stats.png"))
        self.label_4.setScaledContents(True)
        self.stats_btn = QPushButton(self.stats_lbl)
        self.stats_btn.setObjectName(u"stats_btn")
        self.stats_btn.setGeometry(QRect(0, 0, 231, 81))
        self.stats_btn.setStyleSheet(u"\n"
"background-color: rgba(0,0,0,0);\n"
"")

        self.options.addWidget(self.stats_lbl)

        self.products_lbl = QFrame(self.verticalLayoutWidget)
        self.products_lbl.setObjectName(u"products_lbl")
        self.products_lbl.setFrameShape(QFrame.StyledPanel)
        self.products_lbl.setFrameShadow(QFrame.Raised)
        self.label_7 = QLabel(self.products_lbl)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 10, 51, 51))
        self.label_7.setMaximumSize(QSize(51, 51))
        self.label_7.setBaseSize(QSize(30, 30))
        self.label_7.setFont(font5)
        self.label_7.setPixmap(QPixmap(u":/icons/products.png"))
        self.label_7.setScaledContents(True)
        self.label_6 = QLabel(self.products_lbl)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(80, 10, 131, 51))
        self.label_6.setBaseSize(QSize(50, 20))
        self.label_6.setFont(font4)
        self.label_6.setToolTipDuration(-1)
        self.label_6.setAutoFillBackground(False)
        self.label_6.setStyleSheet(u"QLabel:pressed{\n"
"color:red;\n"
"}\n"
"")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_6.setIndent(1)
        self.products_btn = QPushButton(self.products_lbl)
        self.products_btn.setObjectName(u"products_btn")
        self.products_btn.setGeometry(QRect(0, 0, 231, 81))
        self.products_btn.setStyleSheet(u"\n"
"background-color: rgba(0,0,0,0);\n"
"")

        self.options.addWidget(self.products_lbl)

        self.categories_lbl = QFrame(self.verticalLayoutWidget)
        self.categories_lbl.setObjectName(u"categories_lbl")
        self.categories_lbl.setEnabled(True)
        self.categories_lbl.setFrameShape(QFrame.StyledPanel)
        self.categories_lbl.setFrameShadow(QFrame.Raised)
        self.label_8 = QLabel(self.categories_lbl)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 10, 51, 51))
        self.label_8.setMaximumSize(QSize(51, 51))
        self.label_8.setBaseSize(QSize(30, 30))
        self.label_8.setFont(font5)
        self.label_8.setPixmap(QPixmap(u":/icons/categories.png"))
        self.label_8.setScaledContents(True)
        self.label_10 = QLabel(self.categories_lbl)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(70, 10, 161, 51))
        self.label_10.setBaseSize(QSize(50, 20))
        self.label_10.setFont(font4)
        self.label_10.setAutoFillBackground(False)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.categories_btn = QPushButton(self.categories_lbl)
        self.categories_btn.setObjectName(u"categories_btn")
        self.categories_btn.setGeometry(QRect(10, 0, 221, 81))
        self.categories_btn.setStyleSheet(u"\n"
"background-color: rgba(0,0,0,0);\n"
"")

        self.options.addWidget(self.categories_lbl)

        self.users_lbl = QFrame(self.verticalLayoutWidget)
        self.users_lbl.setObjectName(u"users_lbl")
        self.users_lbl.setFrameShape(QFrame.StyledPanel)
        self.users_lbl.setFrameShadow(QFrame.Raised)
        self.label_9 = QLabel(self.users_lbl)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(70, 10, 159, 51))
        self.label_9.setBaseSize(QSize(50, 20))
        self.label_9.setFont(font4)
        self.label_9.setAutoFillBackground(False)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_11 = QLabel(self.users_lbl)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 10, 51, 51))
        self.label_11.setMaximumSize(QSize(51, 51))
        self.label_11.setBaseSize(QSize(30, 30))
        self.label_11.setFont(font5)
        self.label_11.setPixmap(QPixmap(u":/icons/employee.png"))
        self.label_11.setScaledContents(True)
        self.users_btn = QPushButton(self.users_lbl)
        self.users_btn.setObjectName(u"users_btn")
        self.users_btn.setGeometry(QRect(0, 0, 231, 81))
        self.users_btn.setStyleSheet(u"\n"
"background-color: rgba(0,0,0,0);\n"
"")

        self.options.addWidget(self.users_lbl)

        self.incomes_lbl = QFrame(self.verticalLayoutWidget)
        self.incomes_lbl.setObjectName(u"incomes_lbl")
        self.incomes_lbl.setFrameShape(QFrame.StyledPanel)
        self.incomes_lbl.setFrameShadow(QFrame.Raised)
        self.label_13 = QLabel(self.incomes_lbl)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 10, 51, 51))
        self.label_13.setMaximumSize(QSize(51, 51))
        self.label_13.setBaseSize(QSize(30, 30))
        self.label_13.setFont(font5)
        self.label_13.setPixmap(QPixmap(u":/icons/sellings.png"))
        self.label_13.setScaledContents(True)
        self.label_12 = QLabel(self.incomes_lbl)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(70, 10, 141, 51))
        self.label_12.setBaseSize(QSize(50, 20))
        self.label_12.setFont(font4)
        self.label_12.setAutoFillBackground(False)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.incomes_btn = QPushButton(self.incomes_lbl)
        self.incomes_btn.setObjectName(u"incomes_btn")
        self.incomes_btn.setGeometry(QRect(0, 0, 231, 81))
        self.incomes_btn.setStyleSheet(u"\n"
"background-color: rgba(0,0,0,0);\n"
"")

        self.options.addWidget(self.incomes_lbl)

        self.expenses_lbl = QFrame(self.verticalLayoutWidget)
        self.expenses_lbl.setObjectName(u"expenses_lbl")
        self.expenses_lbl.setEnabled(True)
        self.expenses_lbl.setFrameShape(QFrame.StyledPanel)
        self.expenses_lbl.setFrameShadow(QFrame.Raised)
        self.label_15 = QLabel(self.expenses_lbl)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(20, 10, 51, 51))
        self.label_15.setMaximumSize(QSize(51, 51))
        self.label_15.setBaseSize(QSize(30, 30))
        self.label_15.setFont(font5)
        self.label_15.setPixmap(QPixmap(u":/icons/bills.png"))
        self.label_15.setScaledContents(True)
        self.label_14 = QLabel(self.expenses_lbl)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(60, 10, 151, 51))
        self.label_14.setBaseSize(QSize(50, 20))
        self.label_14.setFont(font4)
        self.label_14.setAutoFillBackground(False)
        self.label_14.setAlignment(Qt.AlignCenter)
        self.expenses_btn = QPushButton(self.expenses_lbl)
        self.expenses_btn.setObjectName(u"expenses_btn")
        self.expenses_btn.setGeometry(QRect(0, 0, 231, 81))
        self.expenses_btn.setStyleSheet(u"\n"
"background-color: rgba(0,0,0,0);\n"
"")

        self.options.addWidget(self.expenses_lbl)

        self.logout_btn = QPushButton(Form)
        self.logout_btn.setObjectName(u"logout_btn")
        self.logout_btn.setGeometry(QRect(20, 730, 31, 41))
        font6 = QFont()
        font6.setStrikeOut(False)
        self.logout_btn.setFont(font6)
        self.logout_btn.setCursor(QCursor(Qt.PointingHandCursor))
        self.logout_btn.setMouseTracking(False)
        self.logout_btn.setTabletTracking(False)
        self.logout_btn.setStyleSheet(u"QPushButton{\n"
"	border-image: url(:/icons/logout.png);\n"
"}\n"
"QPushButton:pressed{\n"
"}")
        self.pushButton_2 = QPushButton(Form)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(70, 730, 41, 41))
        self.pushButton_2.setFont(font6)
        self.pushButton_2.setCursor(QCursor(Qt.PointingHandCursor))
        self.pushButton_2.setMouseTracking(False)
        self.pushButton_2.setTabletTracking(False)
        self.pushButton_2.setStyleSheet(u"border-image: url(:/icons/settings.png);")
#if QT_CONFIG(shortcut)
#endif // QT_CONFIG(shortcut)
        QWidget.setTabOrder(self.users_id, self.users_first_name)
        QWidget.setTabOrder(self.users_first_name, self.users_last_name)
        QWidget.setTabOrder(self.users_last_name, self.users_birth_date)
        QWidget.setTabOrder(self.users_birth_date, self.users_phone_number)
        QWidget.setTabOrder(self.users_phone_number, self.users_salary)
        QWidget.setTabOrder(self.users_salary, self.users_male)
        QWidget.setTabOrder(self.users_male, self.users_female)
        QWidget.setTabOrder(self.users_female, self.users_adress)
        QWidget.setTabOrder(self.users_adress, self.users_user_name)
        QWidget.setTabOrder(self.users_user_name, self.users_password)
        QWidget.setTabOrder(self.users_password, self.users_role)
        QWidget.setTabOrder(self.users_role, self.users_add_btn)
        QWidget.setTabOrder(self.users_add_btn, self.users_update_btn)
        QWidget.setTabOrder(self.users_update_btn, self.users_delete_btn)
        QWidget.setTabOrder(self.users_delete_btn, self.users_clear_btn)
        QWidget.setTabOrder(self.users_clear_btn, self.users_search_btn)
        QWidget.setTabOrder(self.users_search_btn, self.users_table)
        QWidget.setTabOrder(self.users_table, self.products_search_btn)
        QWidget.setTabOrder(self.products_search_btn, self.category_name)
        QWidget.setTabOrder(self.category_name, self.category_id)
        QWidget.setTabOrder(self.category_id, self.categories_clear_btn)
        QWidget.setTabOrder(self.categories_clear_btn, self.categories_add_btn)
        QWidget.setTabOrder(self.categories_add_btn, self.categories_update_btn)
        QWidget.setTabOrder(self.categories_update_btn, self.categories_delete_btn)
        QWidget.setTabOrder(self.categories_delete_btn, self.tableWidget_2)
        QWidget.setTabOrder(self.tableWidget_2, self.categories_search_btn)
        QWidget.setTabOrder(self.categories_search_btn, self.textEdit_2)
        QWidget.setTabOrder(self.textEdit_2, self.logout_btn)
        QWidget.setTabOrder(self.logout_btn, self.products_btn)
        QWidget.setTabOrder(self.products_btn, self.pushButton_2)
        QWidget.setTabOrder(self.pushButton_2, self.stats_btn)
        QWidget.setTabOrder(self.stats_btn, self.incomes_btn)
        QWidget.setTabOrder(self.incomes_btn, self.expenses_btn)
        QWidget.setTabOrder(self.expenses_btn, self.product_id)
        QWidget.setTabOrder(self.product_id, self.product_name)
        QWidget.setTabOrder(self.product_name, self.product_price)
        QWidget.setTabOrder(self.product_price, self.categories_btn)
        QWidget.setTabOrder(self.categories_btn, self.users_btn)
        QWidget.setTabOrder(self.users_btn, self.tableWidget)
        QWidget.setTabOrder(self.tableWidget, self.product_quantity)
        QWidget.setTabOrder(self.product_quantity, self.add_btn)
        QWidget.setTabOrder(self.add_btn, self.update_btn)
        QWidget.setTabOrder(self.update_btn, self.delete_btn)
        QWidget.setTabOrder(self.delete_btn, self.product_category)
        QWidget.setTabOrder(self.product_category, self.clear_btn)
        QWidget.setTabOrder(self.clear_btn, self.categorie_id_9)
        QWidget.setTabOrder(self.categorie_id_9, self.categorie_id_10)
        QWidget.setTabOrder(self.categorie_id_10, self.categorie_id_11)
        QWidget.setTabOrder(self.categorie_id_11, self.categorie_id_12)
        QWidget.setTabOrder(self.categorie_id_12, self.sellings_search_btn)
        QWidget.setTabOrder(self.sellings_search_btn, self.sellings_delete_btn)
        QWidget.setTabOrder(self.sellings_delete_btn, self.tableWidget_4)
        QWidget.setTabOrder(self.tableWidget_4, self.expense_delete_btn)
        QWidget.setTabOrder(self.expense_delete_btn, self.expense_id)
        QWidget.setTabOrder(self.expense_id, self.tableWidget_5)
        QWidget.setTabOrder(self.tableWidget_5, self.expense_clear_btn)
        QWidget.setTabOrder(self.expense_clear_btn, self.expense_update_btn)
        QWidget.setTabOrder(self.expense_update_btn, self.expense_search_btn)
        QWidget.setTabOrder(self.expense_search_btn, self.expense_description)
        QWidget.setTabOrder(self.expense_description, self.expense_ammount)
        QWidget.setTabOrder(self.expense_ammount, self.expense_add_btn)
        QWidget.setTabOrder(self.expense_add_btn, self.expense_type)
        QWidget.setTabOrder(self.expense_type, self.expense_date)

        self.retranslateUi(Form)

        self.containor.setCurrentIndex(2)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
#if QT_CONFIG(statustip)
        Form.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.groupBox.setTitle("")
        self.label.setText("")
        self.admin_name_lbl.setText(QCoreApplication.translate("Form", u"admin name here", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"ADMIN", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"STATS", None))
        ___qtablewidgetitem = self.tableWidget.horizontalHeaderItem(0)
        ___qtablewidgetitem.setText(QCoreApplication.translate("Form", u"ID", None));
        ___qtablewidgetitem1 = self.tableWidget.horizontalHeaderItem(1)
        ___qtablewidgetitem1.setText(QCoreApplication.translate("Form", u"Name", None));
        ___qtablewidgetitem2 = self.tableWidget.horizontalHeaderItem(2)
        ___qtablewidgetitem2.setText(QCoreApplication.translate("Form", u"Category", None));
        ___qtablewidgetitem3 = self.tableWidget.horizontalHeaderItem(3)
        ___qtablewidgetitem3.setText(QCoreApplication.translate("Form", u"Price", None));
        ___qtablewidgetitem4 = self.tableWidget.horizontalHeaderItem(4)
        ___qtablewidgetitem4.setText(QCoreApplication.translate("Form", u"Quantity", None));
        self.label_19.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_24.setText(QCoreApplication.translate("Form", u"Price", None))
        self.label_25.setText(QCoreApplication.translate("Form", u"Quantity", None))
        self.label_26.setText(QCoreApplication.translate("Form", u"ID", None))
        self.product_id.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Id", None))
        self.product_name.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Name", None))
        self.product_price.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Price", None))
        self.product_quantity.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Quantity", None))
#if QT_CONFIG(statustip)
        self.add_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.add_btn.setText(QCoreApplication.translate("Form", u"Add", None))
#if QT_CONFIG(statustip)
        self.update_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.update_btn.setText(QCoreApplication.translate("Form", u"Update", None))
#if QT_CONFIG(statustip)
        self.delete_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.delete_btn.setText(QCoreApplication.translate("Form", u"Delete", None))
        self.product_category.setItemText(0, QCoreApplication.translate("Form", u"computer", None))
        self.product_category.setItemText(1, QCoreApplication.translate("Form", u"fish", None))
        self.product_category.setItemText(2, QCoreApplication.translate("Form", u"gold", None))
        self.product_category.setItemText(3, QCoreApplication.translate("Form", u"phone", None))

#if QT_CONFIG(statustip)
        self.clear_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.clear_btn.setText(QCoreApplication.translate("Form", u"Clear", None))
        self.label_16.setText("")
        self.label_17.setText(QCoreApplication.translate("Form", u"Products", None))
#if QT_CONFIG(statustip)
        self.products_search_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.products_search_btn.setText(QCoreApplication.translate("Form", u"search", None))
        self.label_27.setText(QCoreApplication.translate("Form", u"Categories", None))
        self.label_20.setText("")
#if QT_CONFIG(statustip)
        self.category_name.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.category_name.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Name", None))
#if QT_CONFIG(statustip)
        self.category_id.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.category_id.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Id", None))
        self.label_28.setText(QCoreApplication.translate("Form", u"Description", None))
        self.label_29.setText(QCoreApplication.translate("Form", u"Name", None))
        self.label_30.setText(QCoreApplication.translate("Form", u"ID", None))
#if QT_CONFIG(statustip)
        self.categories_clear_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.categories_clear_btn.setText(QCoreApplication.translate("Form", u"Clear", None))
#if QT_CONFIG(statustip)
        self.categories_add_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.categories_add_btn.setText(QCoreApplication.translate("Form", u"Add", None))
#if QT_CONFIG(statustip)
        self.categories_update_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.categories_update_btn.setText(QCoreApplication.translate("Form", u"Update", None))
#if QT_CONFIG(statustip)
        self.categories_delete_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.categories_delete_btn.setText(QCoreApplication.translate("Form", u"Delete", None))
        ___qtablewidgetitem5 = self.tableWidget_2.horizontalHeaderItem(0)
        ___qtablewidgetitem5.setText(QCoreApplication.translate("Form", u"ID", None));
        ___qtablewidgetitem6 = self.tableWidget_2.horizontalHeaderItem(1)
        ___qtablewidgetitem6.setText(QCoreApplication.translate("Form", u"Name", None));
        ___qtablewidgetitem7 = self.tableWidget_2.horizontalHeaderItem(2)
        ___qtablewidgetitem7.setText(QCoreApplication.translate("Form", u"Description", None));
#if QT_CONFIG(statustip)
        self.categories_search_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.categories_search_btn.setText(QCoreApplication.translate("Form", u"search", None))
#if QT_CONFIG(statustip)
        self.textEdit_2.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.textEdit_2.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Description", None))
        self.label_31.setText(QCoreApplication.translate("Form", u"User ID", None))
#if QT_CONFIG(statustip)
        self.users_id.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_id.setPlaceholderText(QCoreApplication.translate("Form", u"Id", None))
        self.label_32.setText(QCoreApplication.translate("Form", u"First Name", None))
        self.label_33.setText(QCoreApplication.translate("Form", u"Last Name", None))
#if QT_CONFIG(statustip)
        self.users_first_name.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_first_name.setPlaceholderText(QCoreApplication.translate("Form", u"Enter First Name", None))
#if QT_CONFIG(statustip)
        self.users_last_name.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_last_name.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Last Name", None))
        self.label_34.setText(QCoreApplication.translate("Form", u"Birth Date", None))
        self.label_35.setText(QCoreApplication.translate("Form", u"Gender", None))
        self.users_male.setText(QCoreApplication.translate("Form", u"Male", None))
        self.users_female.setText(QCoreApplication.translate("Form", u"Female", None))
        self.label_36.setText(QCoreApplication.translate("Form", u"User's Account", None))
        self.label_37.setText(QCoreApplication.translate("Form", u"User Name", None))
#if QT_CONFIG(statustip)
        self.users_user_name.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_user_name.setPlaceholderText(QCoreApplication.translate("Form", u"Enter User Name", None))
        self.label_38.setText(QCoreApplication.translate("Form", u"Password", None))
#if QT_CONFIG(statustip)
        self.users_password.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_password.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Password", None))
        self.label_39.setText(QCoreApplication.translate("Form", u"Role", None))
        self.users_role.setItemText(0, QCoreApplication.translate("Form", u"Admin", None))
        self.users_role.setItemText(1, QCoreApplication.translate("Form", u"Seller", None))

        self.label_40.setText(QCoreApplication.translate("Form", u"Phone Number", None))
#if QT_CONFIG(statustip)
        self.users_phone_number.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_phone_number.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Phone Number", None))
        self.label_41.setText(QCoreApplication.translate("Form", u"Salary", None))
#if QT_CONFIG(statustip)
        self.users_salary.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_salary.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Salary", None))
        self.label_42.setText(QCoreApplication.translate("Form", u"Adress", None))
#if QT_CONFIG(statustip)
        self.users_adress.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_adress.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Adress", None))
        self.label_21.setText("")
        self.label_43.setText(QCoreApplication.translate("Form", u"Users", None))
#if QT_CONFIG(statustip)
        self.users_add_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.users_add_btn.setText(QCoreApplication.translate("Form", u"Add", None))
#if QT_CONFIG(statustip)
        self.users_update_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.users_update_btn.setText(QCoreApplication.translate("Form", u"Update", None))
#if QT_CONFIG(statustip)
        self.users_delete_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.users_delete_btn.setText(QCoreApplication.translate("Form", u"Delete", None))
#if QT_CONFIG(statustip)
        self.users_clear_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.users_clear_btn.setText(QCoreApplication.translate("Form", u"Clear", None))
#if QT_CONFIG(statustip)
        self.users_search_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.users_search_btn.setText(QCoreApplication.translate("Form", u"Search", None))
        ___qtablewidgetitem8 = self.users_table.horizontalHeaderItem(0)
        ___qtablewidgetitem8.setText(QCoreApplication.translate("Form", u"ID", None));
        ___qtablewidgetitem9 = self.users_table.horizontalHeaderItem(1)
        ___qtablewidgetitem9.setText(QCoreApplication.translate("Form", u"Fist Name", None));
        ___qtablewidgetitem10 = self.users_table.horizontalHeaderItem(2)
        ___qtablewidgetitem10.setText(QCoreApplication.translate("Form", u"Last Name", None));
        ___qtablewidgetitem11 = self.users_table.horizontalHeaderItem(3)
        ___qtablewidgetitem11.setText(QCoreApplication.translate("Form", u"Birth Date", None));
        ___qtablewidgetitem12 = self.users_table.horizontalHeaderItem(4)
        ___qtablewidgetitem12.setText(QCoreApplication.translate("Form", u"Phone", None));
        ___qtablewidgetitem13 = self.users_table.horizontalHeaderItem(5)
        ___qtablewidgetitem13.setText(QCoreApplication.translate("Form", u"Salary", None));
        ___qtablewidgetitem14 = self.users_table.horizontalHeaderItem(6)
        ___qtablewidgetitem14.setText(QCoreApplication.translate("Form", u"gender", None));
        ___qtablewidgetitem15 = self.users_table.horizontalHeaderItem(7)
        ___qtablewidgetitem15.setText(QCoreApplication.translate("Form", u"adress", None));
        ___qtablewidgetitem16 = self.users_table.horizontalHeaderItem(8)
        ___qtablewidgetitem16.setText(QCoreApplication.translate("Form", u"Role", None));
        ___qtablewidgetitem17 = self.users_table.horizontalHeaderItem(9)
        ___qtablewidgetitem17.setText(QCoreApplication.translate("Form", u"User Name", None));
        ___qtablewidgetitem18 = self.users_table.horizontalHeaderItem(10)
        ___qtablewidgetitem18.setText(QCoreApplication.translate("Form", u"Password", None));
#if QT_CONFIG(statustip)
        self.users_table.setStatusTip("")
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.users_search_id.setStatusTip(QCoreApplication.translate("Form", u"del", None))
#endif // QT_CONFIG(statustip)
        self.users_search_id.setPlaceholderText(QCoreApplication.translate("Form", u"Id", None))
        self.label_44.setText("")
        self.label_45.setText(QCoreApplication.translate("Form", u"Incomes", None))
        self.label_46.setText(QCoreApplication.translate("Form", u"ID", None))
        self.categorie_id_9.setPlaceholderText(QCoreApplication.translate("Form", u"Enter User Name", None))
        self.label_47.setText(QCoreApplication.translate("Form", u"Seller Name", None))
        self.label_48.setText(QCoreApplication.translate("Form", u"Date", None))
        self.label_49.setText(QCoreApplication.translate("Form", u"Total price", None))
        self.categorie_id_10.setPlaceholderText(QCoreApplication.translate("Form", u"Enter User Name", None))
        self.categorie_id_11.setPlaceholderText(QCoreApplication.translate("Form", u"Enter User Name", None))
        self.categorie_id_12.setPlaceholderText(QCoreApplication.translate("Form", u"Enter User Name", None))
#if QT_CONFIG(statustip)
        self.sellings_search_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.sellings_search_btn.setText(QCoreApplication.translate("Form", u"Search", None))
#if QT_CONFIG(statustip)
        self.sellings_delete_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.sellings_delete_btn.setText(QCoreApplication.translate("Form", u"Delete", None))
        ___qtablewidgetitem19 = self.tableWidget_4.horizontalHeaderItem(0)
        ___qtablewidgetitem19.setText(QCoreApplication.translate("Form", u"Sell ID", None));
        ___qtablewidgetitem20 = self.tableWidget_4.horizontalHeaderItem(1)
        ___qtablewidgetitem20.setText(QCoreApplication.translate("Form", u"Seller Name", None));
        ___qtablewidgetitem21 = self.tableWidget_4.horizontalHeaderItem(2)
        ___qtablewidgetitem21.setText(QCoreApplication.translate("Form", u"date", None));
        ___qtablewidgetitem22 = self.tableWidget_4.horizontalHeaderItem(3)
        ___qtablewidgetitem22.setText(QCoreApplication.translate("Form", u"Total", None));
        ___qtablewidgetitem23 = self.tableWidget_4.verticalHeaderItem(0)
        ___qtablewidgetitem23.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem24 = self.tableWidget_4.verticalHeaderItem(2)
        ___qtablewidgetitem24.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem25 = self.tableWidget_4.verticalHeaderItem(3)
        ___qtablewidgetitem25.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem26 = self.tableWidget_4.verticalHeaderItem(4)
        ___qtablewidgetitem26.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem27 = self.tableWidget_4.verticalHeaderItem(5)
        ___qtablewidgetitem27.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem28 = self.tableWidget_4.verticalHeaderItem(6)
        ___qtablewidgetitem28.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem29 = self.tableWidget_4.verticalHeaderItem(7)
        ___qtablewidgetitem29.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem30 = self.tableWidget_4.verticalHeaderItem(8)
        ___qtablewidgetitem30.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem31 = self.tableWidget_4.verticalHeaderItem(9)
        ___qtablewidgetitem31.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem32 = self.tableWidget_4.verticalHeaderItem(10)
        ___qtablewidgetitem32.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem33 = self.tableWidget_4.verticalHeaderItem(11)
        ___qtablewidgetitem33.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem34 = self.tableWidget_4.verticalHeaderItem(12)
        ___qtablewidgetitem34.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem35 = self.tableWidget_4.verticalHeaderItem(13)
        ___qtablewidgetitem35.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem36 = self.tableWidget_4.verticalHeaderItem(14)
        ___qtablewidgetitem36.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem37 = self.tableWidget_4.verticalHeaderItem(15)
        ___qtablewidgetitem37.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem38 = self.tableWidget_4.verticalHeaderItem(16)
        ___qtablewidgetitem38.setText(QCoreApplication.translate("Form", u"New Row", None));
        ___qtablewidgetitem39 = self.tableWidget_4.verticalHeaderItem(17)
        ___qtablewidgetitem39.setText(QCoreApplication.translate("Form", u"New Row", None));
#if QT_CONFIG(statustip)
        self.tableWidget_4.setStatusTip("")
#endif // QT_CONFIG(statustip)
        self.label_50.setText("")
        self.label_51.setText(QCoreApplication.translate("Form", u"Expenses", None))
#if QT_CONFIG(statustip)
        self.expense_delete_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.expense_delete_btn.setText(QCoreApplication.translate("Form", u"Delete", None))
        self.expense_id.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Id", None))
        self.label_52.setText(QCoreApplication.translate("Form", u"ID", None))
        self.label_53.setText(QCoreApplication.translate("Form", u"Ammount", None))
        ___qtablewidgetitem40 = self.tableWidget_5.horizontalHeaderItem(0)
        ___qtablewidgetitem40.setText(QCoreApplication.translate("Form", u"ID", None));
        ___qtablewidgetitem41 = self.tableWidget_5.horizontalHeaderItem(1)
        ___qtablewidgetitem41.setText(QCoreApplication.translate("Form", u"Name", None));
        ___qtablewidgetitem42 = self.tableWidget_5.horizontalHeaderItem(2)
        ___qtablewidgetitem42.setText(QCoreApplication.translate("Form", u"Category", None));
        ___qtablewidgetitem43 = self.tableWidget_5.horizontalHeaderItem(3)
        ___qtablewidgetitem43.setText(QCoreApplication.translate("Form", u"Price", None));
        ___qtablewidgetitem44 = self.tableWidget_5.horizontalHeaderItem(4)
        ___qtablewidgetitem44.setText(QCoreApplication.translate("Form", u"Quantity", None));
#if QT_CONFIG(statustip)
        self.expense_clear_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.expense_clear_btn.setText(QCoreApplication.translate("Form", u"Clear", None))
#if QT_CONFIG(statustip)
        self.expense_update_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.expense_update_btn.setText(QCoreApplication.translate("Form", u"Update", None))
#if QT_CONFIG(statustip)
        self.expense_search_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.expense_search_btn.setText(QCoreApplication.translate("Form", u"search", None))
        self.expense_description.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Description", None))
        self.label_54.setText(QCoreApplication.translate("Form", u"Description", None))
        self.expense_ammount.setPlaceholderText(QCoreApplication.translate("Form", u"Enter Ammount", None))
#if QT_CONFIG(statustip)
        self.expense_add_btn.setStatusTip(QCoreApplication.translate("Form", u"btn_frm", None))
#endif // QT_CONFIG(statustip)
        self.expense_add_btn.setText(QCoreApplication.translate("Form", u"Add", None))
        self.expense_type.setItemText(0, QCoreApplication.translate("Form", u"Salary", None))
        self.expense_type.setItemText(1, QCoreApplication.translate("Form", u"birra3", None))

        self.label_55.setText(QCoreApplication.translate("Form", u"Type", None))
        self.label_56.setText(QCoreApplication.translate("Form", u"Date", None))
#if QT_CONFIG(statustip)
        self.stats_lbl.setStatusTip(QCoreApplication.translate("Form", u"option", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.label_5.setStatusTip(QCoreApplication.translate("Form", u"this", None))
#endif // QT_CONFIG(statustip)
        self.label_5.setText(QCoreApplication.translate("Form", u"Stats", None))
        self.label_4.setText("")
        self.stats_btn.setText("")
#if QT_CONFIG(statustip)
        self.products_lbl.setStatusTip(QCoreApplication.translate("Form", u"option", None))
#endif // QT_CONFIG(statustip)
        self.label_7.setText("")
#if QT_CONFIG(statustip)
        self.label_6.setStatusTip(QCoreApplication.translate("Form", u"this", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(whatsthis)
        self.label_6.setWhatsThis(QCoreApplication.translate("Form", u"this", None))
#endif // QT_CONFIG(whatsthis)
        self.label_6.setText(QCoreApplication.translate("Form", u"Products", None))
        self.products_btn.setText("")
#if QT_CONFIG(statustip)
        self.categories_lbl.setStatusTip(QCoreApplication.translate("Form", u"option", None))
#endif // QT_CONFIG(statustip)
        self.label_8.setText("")
#if QT_CONFIG(statustip)
        self.label_10.setStatusTip(QCoreApplication.translate("Form", u"this", None))
#endif // QT_CONFIG(statustip)
        self.label_10.setText(QCoreApplication.translate("Form", u"Categories", None))
        self.categories_btn.setText("")
#if QT_CONFIG(statustip)
        self.users_lbl.setStatusTip(QCoreApplication.translate("Form", u"option", None))
#endif // QT_CONFIG(statustip)
#if QT_CONFIG(statustip)
        self.label_9.setStatusTip(QCoreApplication.translate("Form", u"this", None))
#endif // QT_CONFIG(statustip)
        self.label_9.setText(QCoreApplication.translate("Form", u"Users", None))
        self.label_11.setText("")
        self.users_btn.setText("")
#if QT_CONFIG(statustip)
        self.incomes_lbl.setStatusTip(QCoreApplication.translate("Form", u"option", None))
#endif // QT_CONFIG(statustip)
        self.label_13.setText("")
#if QT_CONFIG(statustip)
        self.label_12.setStatusTip(QCoreApplication.translate("Form", u"this", None))
#endif // QT_CONFIG(statustip)
        self.label_12.setText(QCoreApplication.translate("Form", u"Incomes", None))
        self.incomes_btn.setText("")
#if QT_CONFIG(statustip)
        self.expenses_lbl.setStatusTip(QCoreApplication.translate("Form", u"option", None))
#endif // QT_CONFIG(statustip)
        self.label_15.setText("")
#if QT_CONFIG(statustip)
        self.label_14.setStatusTip(QCoreApplication.translate("Form", u"this", None))
#endif // QT_CONFIG(statustip)
        self.label_14.setText(QCoreApplication.translate("Form", u"Expenses", None))
        self.expenses_btn.setText("")
        self.logout_btn.setText("")
        self.pushButton_2.setText("")
    # retranslateUi

